# Generated by Django 5.1.1 on 2025-09-03 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('motto', models.CharField(blank=True, max_length=200)),
                ('max_members', models.IntegerField(default=50)),
                ('is_open', models.BooleanField(default=True)),
                ('required_level', models.IntegerField(default=1)),
                ('guild_gold', models.IntegerField(default=0)),
                ('guild_experience', models.IntegerField(default=0)),
                ('guild_level', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_guild', to='players.player')),
            ],
            options={
                'verbose_name': 'Gremio',
                'verbose_name_plural': 'Gremios',
                'ordering': ['-guild_level', '-guild_experience'],
            },
        ),
        migrations.CreateModel(
            name='GuildMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('member', 'Miembro'), ('officer', 'Oficial'), ('lieutenant', 'Teniente'), ('captain', 'Capitán'), ('admiral', 'Almirante'), ('leader', 'Líder')], default='member', max_length=20)),
                ('gold_contributed', models.IntegerField(default=0)),
                ('experience_contributed', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='guilds.guild')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guild_membership', to='players.player')),
            ],
            options={
                'verbose_name': 'Membresía de Gremio',
                'verbose_name_plural': 'Membresías de Gremios',
            },
        ),
    ]
