# Generated by Django 5.1.1 on 2025-09-02 23:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("exploration", "0001_initial"),
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShipType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("balandra", "Balandra"),
                            ("bergantin", "Bergantín"),
                            ("fragata", "Fragata"),
                            ("galeon", "Galeón"),
                            ("navio", "Navío de Línea"),
                            ("corsario", "Corsario"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("base_health", models.PositiveIntegerField()),
                ("base_attack", models.PositiveIntegerField()),
                ("base_defense", models.PositiveIntegerField()),
                ("base_speed", models.PositiveIntegerField()),
                ("base_cargo_capacity", models.PositiveIntegerField()),
                ("base_crew_capacity", models.PositiveIntegerField()),
                ("required_level", models.PositiveIntegerField(default=1)),
                ("required_navigation_skill", models.PositiveIntegerField(default=1)),
                ("gold_cost", models.PositiveIntegerField()),
                ("wood_cost", models.PositiveIntegerField()),
                ("iron_cost", models.PositiveIntegerField()),
                ("exploration_bonus", models.PositiveIntegerField(default=0)),
                ("combat_bonus", models.PositiveIntegerField(default=0)),
                ("trade_bonus", models.PositiveIntegerField(default=0)),
                ("speed_bonus", models.PositiveIntegerField(default=0)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="ships/types/"),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Font Awesome icon class", max_length=50
                    ),
                ),
            ],
            options={
                "verbose_name": "Ship Type",
                "verbose_name_plural": "Ship Types",
                "db_table": "ships_shiptype",
            },
        ),
        migrations.CreateModel(
            name="Ship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("current_health", models.PositiveIntegerField()),
                ("max_health", models.PositiveIntegerField()),
                ("attack", models.PositiveIntegerField()),
                ("defense", models.PositiveIntegerField()),
                ("speed", models.PositiveIntegerField()),
                ("cargo_capacity", models.PositiveIntegerField()),
                ("crew_capacity", models.PositiveIntegerField()),
                ("current_crew", models.PositiveIntegerField(default=0)),
                (
                    "crew_morale",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "condition",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Ship condition percentage",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("is_traveling", models.BooleanField(default=False)),
                ("travel_started", models.DateTimeField(blank=True, null=True)),
                ("travel_arrives", models.DateTimeField(blank=True, null=True)),
                ("cargo_gold", models.PositiveIntegerField(default=0)),
                ("cargo_wood", models.PositiveIntegerField(default=0)),
                ("cargo_iron", models.PositiveIntegerField(default=0)),
                ("cargo_food", models.PositiveIntegerField(default=0)),
                ("cargo_ammunition", models.PositiveIntegerField(default=0)),
                ("cargo_spices", models.PositiveIntegerField(default=0)),
                ("cargo_silk", models.PositiveIntegerField(default=0)),
                ("acquired_at", models.DateTimeField(auto_now_add=True)),
                ("last_maintenance", models.DateTimeField(auto_now_add=True)),
                (
                    "current_region",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ships_present",
                        to="exploration.region",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ships",
                        to="players.player",
                    ),
                ),
                (
                    "travel_destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ships_traveling_to",
                        to="exploration.region",
                    ),
                ),
                (
                    "ship_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ships.shiptype"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ship",
                "verbose_name_plural": "Ships",
                "db_table": "ships_ship",
            },
        ),
        migrations.CreateModel(
            name="ShipUpgrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "upgrade_type",
                    models.CharField(
                        choices=[
                            ("hull", "Hull Reinforcement"),
                            ("sails", "Improved Sails"),
                            ("cannons", "Better Cannons"),
                            ("storage", "Expanded Storage"),
                            ("crew_quarters", "Better Crew Quarters"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("health_bonus", models.IntegerField(default=0)),
                ("attack_bonus", models.IntegerField(default=0)),
                ("defense_bonus", models.IntegerField(default=0)),
                ("speed_bonus", models.IntegerField(default=0)),
                ("cargo_bonus", models.IntegerField(default=0)),
                ("crew_bonus", models.IntegerField(default=0)),
                ("required_level", models.PositiveIntegerField(default=1)),
                ("gold_cost", models.PositiveIntegerField()),
                ("wood_cost", models.PositiveIntegerField(default=0)),
                ("iron_cost", models.PositiveIntegerField(default=0)),
                (
                    "applicable_ship_types",
                    models.ManyToManyField(blank=True, to="ships.shiptype"),
                ),
            ],
            options={
                "verbose_name": "Ship Upgrade",
                "verbose_name_plural": "Ship Upgrades",
                "db_table": "ships_shipupgrade",
            },
        ),
        migrations.CreateModel(
            name="ShipUpgradeInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upgrades",
                        to="ships.ship",
                    ),
                ),
                (
                    "upgrade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ships.shipupgrade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ship Upgrade Instance",
                "verbose_name_plural": "Ship Upgrade Instances",
                "db_table": "ships_shipupgradeinstance",
                "unique_together": {("ship", "upgrade")},
            },
        ),
    ]
