# Generated by Django 5.1.1 on 2025-09-03 01:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exploration', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Carga de Barco',
                'verbose_name_plural': 'Cargas de Barcos',
            },
        ),
        migrations.CreateModel(
            name='ShipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('base_speed', models.IntegerField()),
                ('base_cargo_capacity', models.IntegerField()),
                ('base_firepower', models.IntegerField()),
                ('base_defense', models.IntegerField()),
                ('base_crew_capacity', models.IntegerField()),
                ('purchase_cost', models.IntegerField()),
                ('maintenance_cost_per_day', models.IntegerField()),
                ('required_level', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Tipo de Barco',
                'verbose_name_plural': 'Tipos de Barcos',
                'ordering': ['required_level', 'purchase_cost'],
            },
        ),
        migrations.CreateModel(
            name='ShipUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('upgrade_type', models.CharField(choices=[('speed', 'Velocidad'), ('cargo', 'Capacidad de Carga'), ('firepower', 'Poder de Fuego'), ('defense', 'Defensa'), ('crew', 'Capacidad de Tripulación')], max_length=20)),
                ('bonus_amount', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('required_level', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Mejora de Barco',
                'verbose_name_plural': 'Mejoras de Barcos',
            },
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('docked', 'Atracado'), ('sailing', 'Navegando'), ('exploring', 'Explorando'), ('trading', 'Comerciando'), ('combat', 'En Combate'), ('repairing', 'En Reparación')], default='docked', max_length=20)),
                ('speed', models.IntegerField()),
                ('cargo_capacity', models.IntegerField()),
                ('firepower', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('crew_capacity', models.IntegerField()),
                ('hull_health', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('crew_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_maintenance', models.DateTimeField(auto_now_add=True)),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exploration.region')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='players.player')),
            ],
            options={
                'verbose_name': 'Barco',
                'verbose_name_plural': 'Barcos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crew_type', models.CharField(choices=[('sailor', 'Marinero'), ('gunner', 'Artillero'), ('navigator', 'Navegante'), ('carpenter', 'Carpintero'), ('cook', 'Cocinero'), ('quartermaster', 'Contramaestre')], max_length=20)),
                ('skill_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('salary_per_day', models.IntegerField()),
                ('hired_at', models.DateTimeField(auto_now_add=True)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_members', to='ships.ship')),
            ],
            options={
                'verbose_name': 'Tripulante',
                'verbose_name_plural': 'Tripulantes',
            },
        ),
    ]
