# Generated by Django 5.1.1 on 2025-09-03 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ships', '0001_initial'),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipcargo',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.resource'),
        ),
        migrations.AddField(
            model_name='shipcargo',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_items', to='ships.ship'),
        ),
        migrations.AddField(
            model_name='ship',
            name='ship_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ships.shiptype'),
        ),
        migrations.AlterUniqueTogether(
            name='shipcargo',
            unique_together={('ship', 'resource')},
        ),
    ]
