version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://ageofvoyage:voyage2025@db:5432/ageofvoyage

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ageofvoyage
      - POSTGRES_USER=ageofvoyage
      - POSTGRES_PASSWORD=voyage2025
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ageofvoyage"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://ageofvoyage:voyage2025@db:5432/ageofvoyage

volumes:
  postgres_data:
