# Generated by Django 5.1.1 on 2025-09-03 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exploration', '0001_initial'),
        ('players', '0001_initial'),
        ('ships', '0001_initial'),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorationmission',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ships.ship'),
        ),
        migrations.AddField(
            model_name='region',
            name='discoverer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_regions', to='players.player'),
        ),
        migrations.AddField(
            model_name='explorationmission',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exploration.region'),
        ),
        migrations.AddField(
            model_name='regionresource',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='exploration.region'),
        ),
        migrations.AddField(
            model_name='regionresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.resource'),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('x_coordinate', 'y_coordinate')},
        ),
        migrations.AlterUniqueTogether(
            name='regionresource',
            unique_together={('region', 'resource')},
        ),
    ]
