# Generated by Django 5.1.1 on 2025-09-02 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("exploration", "0001_initial"),
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exploration",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="explorations",
                to="players.player",
            ),
        ),
        migrations.AddField(
            model_name="playerdiscovery",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discoveries",
                to="players.player",
            ),
        ),
        migrations.AddField(
            model_name="playerdiscovery",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discovered_by",
                to="exploration.region",
            ),
        ),
        migrations.AddField(
            model_name="exploration",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="explorations",
                to="exploration.region",
            ),
        ),
        migrations.AddField(
            model_name="travelroute",
            name="from_region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes_from",
                to="exploration.region",
            ),
        ),
        migrations.AddField(
            model_name="travelroute",
            name="to_region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes_to",
                to="exploration.region",
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="world_region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regions",
                to="exploration.worldregion",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="playerdiscovery",
            unique_together={("player", "region")},
        ),
        migrations.AlterUniqueTogether(
            name="travelroute",
            unique_together={("from_region", "to_region")},
        ),
        migrations.AlterUniqueTogether(
            name="region",
            unique_together={("name", "world_region")},
        ),
    ]
