# Generated by Django 5.1.1 on 2025-09-02 23:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("exploration", "0001_initial"),
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commodity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("basic", "Basic Resources"),
                            ("luxury", "Luxury Goods"),
                            ("military", "Military Supplies"),
                            ("food", "Food & Provisions"),
                            ("craft", "Crafted Goods"),
                            ("exotic", "Exotic Items"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("weight_per_unit", models.PositiveIntegerField(default=1)),
                (
                    "demand_volatility",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="How much prices fluctuate (1.0 = normal, higher = more volatile)",
                        max_digits=5,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Font Awesome icon class", max_length=50
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="commodities/"),
                ),
                (
                    "preferred_regions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Regions where this commodity is in higher demand",
                        to="exploration.worldregion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commodity",
                "verbose_name_plural": "Commodities",
                "db_table": "trade_commodity",
            },
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prosperity_level",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Economic prosperity level affecting prices and availability",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "trade_volume",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Daily trade volume affecting price stability",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.05"),
                        help_text="Tax rate as decimal (0.05 = 5%)",
                        max_digits=5,
                    ),
                ),
                (
                    "region",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market",
                        to="exploration.region",
                    ),
                ),
                (
                    "specialized_commodities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Commodities this market specializes in",
                        to="trade.commodity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market",
                "verbose_name_plural": "Markets",
                "db_table": "trade_market",
            },
        ),
        migrations.CreateModel(
            name="TradeContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("delivery", "Delivery Contract"),
                            ("supply", "Supply Contract"),
                            ("exclusive", "Exclusive Deal"),
                            ("bulk", "Bulk Order"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("accepted", "Accepted"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("deadline", models.DateTimeField()),
                (
                    "bonus_payment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "penalty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("required_level", models.PositiveIntegerField(default=1)),
                ("required_reputation", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trade_contracts",
                        to="players.player",
                    ),
                ),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trade.commodity",
                    ),
                ),
                (
                    "delivery_market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_contracts",
                        to="trade.market",
                    ),
                ),
                (
                    "pickup_market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup_contracts",
                        to="trade.market",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trade Contract",
                "verbose_name_plural": "Trade Contracts",
                "db_table": "trade_tradecontract",
            },
        ),
        migrations.CreateModel(
            name="TradeTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("buy", "Purchase"),
                            ("sell", "Sale"),
                            ("contract", "Contract Fulfillment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tax_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="trade.commodity",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="trade.tradecontract",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="trade.market",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_transactions",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trade Transaction",
                "verbose_name_plural": "Trade Transactions",
                "db_table": "trade_tradetransaction",
            },
        ),
        migrations.CreateModel(
            name="MarketPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("buy_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sell_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("supply", models.PositiveIntegerField(default=100)),
                ("demand", models.PositiveIntegerField(default=100)),
                (
                    "price_trend",
                    models.CharField(
                        choices=[
                            ("rising", "Rising"),
                            ("stable", "Stable"),
                            ("falling", "Falling"),
                        ],
                        default="stable",
                        max_length=10,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_prices",
                        to="trade.commodity",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="trade.market",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Price",
                "verbose_name_plural": "Market Prices",
                "db_table": "trade_marketprice",
                "unique_together": {("market", "commodity")},
            },
        ),
        migrations.CreateModel(
            name="PlayerTradeReputation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reputation",
                    models.IntegerField(
                        default=0,
                        help_text="Trade reputation from -100 to +100",
                        validators=[
                            django.core.validators.MinValueValidator(-100),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("total_trades", models.PositiveIntegerField(default=0)),
                (
                    "total_value_traded",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("contracts_completed", models.PositiveIntegerField(default=0)),
                ("contracts_failed", models.PositiveIntegerField(default=0)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_reputations",
                        to="trade.market",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_reputations",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Trade Reputation",
                "verbose_name_plural": "Player Trade Reputations",
                "db_table": "trade_playertradereputation",
                "unique_together": {("player", "market")},
            },
        ),
        migrations.CreateModel(
            name="TradeRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distance",
                    models.PositiveIntegerField(help_text="Distance in nautical miles"),
                ),
                ("established_at", models.DateTimeField(auto_now_add=True)),
                (
                    "popularity",
                    models.PositiveIntegerField(
                        default=1, help_text="How popular this route is with traders"
                    ),
                ),
                (
                    "average_profit_margin",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.0"),
                        help_text="Average profit margin as percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "from_market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes_from",
                        to="trade.market",
                    ),
                ),
                (
                    "to_market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes_to",
                        to="trade.market",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trade Route",
                "verbose_name_plural": "Trade Routes",
                "db_table": "trade_traderoute",
                "unique_together": {("from_market", "to_market")},
            },
        ),
    ]
