# Generated by Django 5.1.1 on 2025-09-02 23:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("exploration", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Faction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("color", models.CharField(help_text="Hex color code", max_length=7)),
                (
                    "emblem",
                    models.ImageField(blank=True, null=True, upload_to="factions/"),
                ),
            ],
            options={
                "verbose_name": "Faction",
                "verbose_name_plural": "Factions",
                "db_table": "players_faction",
            },
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("navigation", "Navigation"),
                            ("combat", "Combat"),
                            ("trade", "Trade"),
                            ("exploration", "Exploration"),
                            ("diplomacy", "Diplomacy"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        help_text="Font Awesome icon class", max_length=50
                    ),
                ),
            ],
            options={
                "verbose_name": "Specialization",
                "verbose_name_plural": "Specializations",
                "db_table": "players_specialization",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("captain_name", models.CharField(max_length=100)),
                ("motto", models.CharField(blank=True, max_length=200)),
                (
                    "flag_design",
                    models.JSONField(
                        default=dict, help_text="Custom flag configuration"
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("experience", models.PositiveIntegerField(default=0)),
                ("experience_to_next_level", models.PositiveIntegerField(default=100)),
                ("gold", models.PositiveIntegerField(default=1000)),
                ("wood", models.PositiveIntegerField(default=100)),
                ("iron", models.PositiveIntegerField(default=50)),
                ("food", models.PositiveIntegerField(default=100)),
                ("ammunition", models.PositiveIntegerField(default=50)),
                ("spices", models.PositiveIntegerField(default=0)),
                ("silk", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_active", models.DateTimeField(auto_now=True)),
                (
                    "current_region",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_players",
                        to="exploration.region",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Player",
                "verbose_name_plural": "Players",
                "db_table": "players_player",
            },
        ),
        migrations.CreateModel(
            name="FactionReputation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reputation",
                    models.IntegerField(
                        default=0,
                        help_text="Reputation range from -100 (hostile) to +100 (allied)",
                        validators=[
                            django.core.validators.MinValueValidator(-100),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "faction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="players.faction",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faction_reputations",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faction Reputation",
                "verbose_name_plural": "Faction Reputations",
                "db_table": "players_factionreputation",
                "unique_together": {("player", "faction")},
            },
        ),
        migrations.CreateModel(
            name="PlayerSpecialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("experience", models.PositiveIntegerField(default=0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specializations",
                        to="players.player",
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="players.specialization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Specialization",
                "verbose_name_plural": "Player Specializations",
                "db_table": "players_playerspecialization",
                "unique_together": {("player", "specialization")},
            },
        ),
    ]
