# Generated by Django 5.1.1 on 2025-09-03 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('mission_type', models.CharField(choices=[('exploration', 'Exploración'), ('trade', 'Comercio'), ('combat', 'Combate'), ('delivery', 'Entrega'), ('escort', 'Escolta'), ('rescue', 'Rescate')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Medio'), ('hard', 'Difícil'), ('extreme', 'Extremo')], max_length=20)),
                ('required_level', models.IntegerField(default=1)),
                ('required_ship_type', models.CharField(blank=True, max_length=50)),
                ('gold_reward', models.IntegerField()),
                ('experience_reward', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('max_attempts', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Misión',
                'verbose_name_plural': 'Misiones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Asignada'), ('in_progress', 'En Progreso'), ('completed', 'Completada'), ('failed', 'Fallida'), ('abandoned', 'Abandonada')], default='assigned', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.mission')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='players.player')),
            ],
            options={
                'verbose_name': 'Misión del Jugador',
                'verbose_name_plural': 'Misiones de Jugadores',
                'unique_together': {('player', 'mission')},
            },
        ),
    ]
