# Generated by Django 5.1.1 on 2025-09-02 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("exploration", "0002_initial"),
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MissionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        help_text="Font Awesome icon class", max_length=50
                    ),
                ),
                ("color", models.CharField(help_text="Hex color code", max_length=7)),
            ],
            options={
                "verbose_name": "Mission Category",
                "verbose_name_plural": "Mission Categories",
                "db_table": "missions_missioncategory",
            },
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "mission_type",
                    models.CharField(
                        choices=[
                            ("story", "Story Mission"),
                            ("side", "Side Mission"),
                            ("daily", "Daily Mission"),
                            ("contract", "Contract Mission"),
                            ("exploration", "Exploration Mission"),
                            ("combat", "Combat Mission"),
                            ("trade", "Trade Mission"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Easy"),
                            (2, "Medium"),
                            (3, "Hard"),
                            (4, "Expert"),
                            (5, "Legendary"),
                        ]
                    ),
                ),
                ("required_level", models.PositiveIntegerField(default=1)),
                (
                    "required_ships",
                    models.JSONField(default=list, help_text="Required ship types"),
                ),
                (
                    "required_reputation",
                    models.JSONField(
                        default=dict, help_text="Required faction reputations"
                    ),
                ),
                (
                    "objectives",
                    models.JSONField(
                        default=list, help_text="List of mission objectives"
                    ),
                ),
                ("experience_reward", models.PositiveIntegerField()),
                ("gold_reward", models.PositiveIntegerField(default=0)),
                (
                    "resource_rewards",
                    models.JSONField(
                        default=dict, help_text="Resource type and quantity rewards"
                    ),
                ),
                (
                    "reputation_rewards",
                    models.JSONField(
                        default=dict, help_text="Faction reputation changes"
                    ),
                ),
                (
                    "special_rewards",
                    models.JSONField(
                        default=list, help_text="Special items, ships, or unlocks"
                    ),
                ),
                (
                    "time_limit",
                    models.DurationField(
                        blank=True,
                        help_text="Time limit for mission completion",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_repeatable", models.BooleanField(default=False)),
                (
                    "max_completions",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum times a player can complete this mission",
                    ),
                ),
                (
                    "prerequisite_missions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Missions that must be completed first",
                        to="missions.mission",
                    ),
                ),
                (
                    "required_regions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Regions that must be discovered",
                        to="exploration.region",
                    ),
                ),
                (
                    "start_region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="starting_missions",
                        to="exploration.region",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to="missions.missioncategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mission",
                "verbose_name_plural": "Missions",
                "db_table": "missions_mission",
            },
        ),
        migrations.CreateModel(
            name="MissionReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("experience", "Experience Points"),
                            ("gold", "Gold"),
                            ("resource", "Resources"),
                            ("item", "Special Item"),
                            ("ship", "Ship"),
                            ("unlock", "Feature Unlock"),
                            ("reputation", "Faction Reputation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("requires_optional_objectives", models.BooleanField(default=False)),
                (
                    "bonus_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Multiplier for bonus conditions",
                        max_digits=4,
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_details",
                        to="missions.mission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mission Reward",
                "verbose_name_plural": "Mission Rewards",
                "db_table": "missions_missionreward",
            },
        ),
        migrations.CreateModel(
            name="QuestGiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField()),
                (
                    "portrait",
                    models.ImageField(blank=True, null=True, upload_to="quest_givers/"),
                ),
                ("required_reputation", models.IntegerField(default=0)),
                ("required_level", models.PositiveIntegerField(default=1)),
                (
                    "faction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quest_givers",
                        to="players.faction",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quest_givers",
                        to="exploration.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quest Giver",
                "verbose_name_plural": "Quest Givers",
                "db_table": "missions_questgiver",
            },
        ),
        migrations.CreateModel(
            name="QuestGiverMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unlock_level", models.PositiveIntegerField(default=1)),
                ("unlock_reputation", models.IntegerField(default=0)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="missions.mission",
                    ),
                ),
                (
                    "prerequisite_missions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="unlocks_missions",
                        to="missions.mission",
                    ),
                ),
                (
                    "quest_giver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="missions.questgiver",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quest Giver Mission",
                "verbose_name_plural": "Quest Giver Missions",
                "db_table": "missions_questgivermission",
                "unique_together": {("quest_giver", "mission")},
            },
        ),
        migrations.AddField(
            model_name="questgiver",
            name="missions",
            field=models.ManyToManyField(
                through="missions.QuestGiverMission", to="missions.mission"
            ),
        ),
        migrations.CreateModel(
            name="MissionObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "objective_type",
                    models.CharField(
                        choices=[
                            ("go_to", "Go to Location"),
                            ("defeat", "Defeat Enemies"),
                            ("collect", "Collect Items"),
                            ("deliver", "Deliver Items"),
                            ("trade", "Complete Trade"),
                            ("discover", "Discover Location"),
                            ("survive", "Survive Duration"),
                            ("escort", "Escort NPC"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                ("target_quantity", models.PositiveIntegerField(default=1)),
                (
                    "target_data",
                    models.JSONField(
                        default=dict, help_text="Additional objective-specific data"
                    ),
                ),
                ("is_optional", models.BooleanField(default=False)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objective_details",
                        to="missions.mission",
                    ),
                ),
                (
                    "target_region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exploration.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mission Objective",
                "verbose_name_plural": "Mission Objectives",
                "db_table": "missions_missionobjective",
                "ordering": ["order"],
                "unique_together": {("mission", "order")},
            },
        ),
        migrations.CreateModel(
            name="PlayerMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("accepted", "Accepted"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "objectives_completed",
                    models.JSONField(
                        default=dict,
                        help_text="Track completion status of each objective",
                    ),
                ),
                (
                    "progress_data",
                    models.JSONField(
                        default=dict, help_text="Store mission-specific progress data"
                    ),
                ),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("completion_count", models.PositiveIntegerField(default=0)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_missions",
                        to="missions.mission",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Mission",
                "verbose_name_plural": "Player Missions",
                "db_table": "missions_playermission",
                "unique_together": {("player", "mission")},
            },
        ),
    ]
