# Generated by Django 5.1.1 on 2025-09-03 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('economic', 'Económico'), ('military', 'Militar'), ('infrastructure', 'Infraestructura'), ('residential', 'Residencial')], max_length=20)),
                ('build_cost', models.IntegerField()),
                ('maintenance_cost', models.IntegerField()),
                ('required_level', models.IntegerField(default=1)),
                ('build_time_hours', models.IntegerField(default=1)),
                ('gold_production', models.IntegerField(default=0)),
                ('defense_bonus', models.IntegerField(default=0)),
                ('storage_capacity', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tipo de Construcción',
                'verbose_name_plural': 'Tipos de Construcciones',
            },
        ),
        migrations.CreateModel(
            name='PlayerBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planning', 'Planificando'), ('building', 'Construyendo'), ('completed', 'Completada'), ('damaged', 'Dañada')], default='planning', max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('construction_started', models.DateTimeField(auto_now_add=True)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.buildingtype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='players.player')),
            ],
            options={
                'verbose_name': 'Construcción del Jugador',
                'verbose_name_plural': 'Construcciones de Jugadores',
            },
        ),
    ]
