# Generated by Django 5.1.1 on 2025-09-03 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        ('exploration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerbuilding',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exploration.region'),
        ),
    ]
