# Generated by Django 5.1.1 on 2025-09-03 01:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('critical_hit', 'Golpe Crítico'), ('miss', 'Fallo'), ('fire', 'Incendio'), ('storm', 'Tormenta'), ('reinforcements', 'Refuerzos'), ('sabotage', 'Sabotaje')], max_length=20)),
                ('description', models.TextField()),
                ('damage_modifier', models.FloatField(default=1.0)),
                ('accuracy_modifier', models.FloatField(default=1.0)),
                ('duration_turns', models.IntegerField(default=1)),
                ('probability', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Evento de Combate',
                'verbose_name_plural': 'Eventos de Combate',
            },
        ),
        migrations.CreateModel(
            name='CombatTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.IntegerField()),
                ('action_type', models.CharField(choices=[('cannon', 'Disparo de Cañón'), ('ram', 'Embestida'), ('board', 'Abordaje'), ('repair', 'Reparación'), ('retreat', 'Retirada')], max_length=20)),
                ('damage_dealt', models.IntegerField(default=0)),
                ('damage_received', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Turno de Combate',
                'verbose_name_plural': 'Turnos de Combate',
                'ordering': ['battle', 'turn_number'],
            },
        ),
        migrations.CreateModel(
            name='PirateFleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fleet_type', models.CharField(choices=[('scout', 'Explorador'), ('raider', 'Asaltante'), ('warship', 'Navío de Guerra'), ('flagship', 'Buque Insignia')], max_length=20)),
                ('firepower', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('crew_size', models.IntegerField()),
                ('level', models.IntegerField(default=1)),
                ('gold_reward', models.IntegerField()),
                ('experience_reward', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Flota Pirata',
                'verbose_name_plural': 'Flotas Piratas',
            },
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_type', models.CharField(choices=[('pvp', 'Jugador vs Jugador'), ('pve', 'Jugador vs NPC'), ('raid', 'Asalto'), ('defense', 'Defensa')], max_length=20)),
                ('status', models.CharField(choices=[('preparing', 'Preparando'), ('in_progress', 'En Progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='preparing', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('gold_stakes', models.IntegerField(default=0)),
                ('experience_reward', models.IntegerField(default=0)),
                ('battle_log', models.TextField(blank=True)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_attacker', to='players.player')),
            ],
            options={
                'verbose_name': 'Batalla',
                'verbose_name_plural': 'Batallas',
                'ordering': ['-started_at'],
            },
        ),
    ]
