# Generated by Django 5.1.1 on 2025-09-03 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('combat', '0001_initial'),
        ('exploration', '0001_initial'),
        ('players', '0001_initial'),
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='attacker_ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_attacker', to='ships.ship'),
        ),
        migrations.AddField(
            model_name='battle',
            name='defender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_defender', to='players.player'),
        ),
        migrations.AddField(
            model_name='battle',
            name='defender_ship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_defender', to='ships.ship'),
        ),
        migrations.AddField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_won', to='players.player'),
        ),
        migrations.AddField(
            model_name='combatturn',
            name='acting_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player'),
        ),
        migrations.AddField(
            model_name='combatturn',
            name='battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='combat.battle'),
        ),
        migrations.AddField(
            model_name='piratefleet',
            name='current_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exploration.region'),
        ),
    ]
