# Generated by Django 5.1.1 on 2025-09-02 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("combat", "0001_initial"),
        ("exploration", "0001_initial"),
        ("players", "0001_initial"),
        ("ships", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="battle",
            name="enemy_player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enemy_battles",
                to="players.player",
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="enemy_ship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enemy_battles",
                to="ships.ship",
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="battles",
                to="exploration.region",
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="battles",
                to="players.player",
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="player_ship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="battles",
                to="ships.ship",
            ),
        ),
        migrations.AddField(
            model_name="battleevent",
            name="battle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="combat.battle",
            ),
        ),
        migrations.AddField(
            model_name="battleturn",
            name="ammunition_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="battle_turns",
                to="combat.ammunitiontype",
            ),
        ),
        migrations.AddField(
            model_name="battleturn",
            name="battle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turns",
                to="combat.battle",
            ),
        ),
        migrations.AddField(
            model_name="battleturn",
            name="action",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="battle_turns",
                to="combat.combataction",
            ),
        ),
        migrations.AddField(
            model_name="battleevent",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="combat.combatevent"
            ),
        ),
        migrations.AddField(
            model_name="piratefleet",
            name="spawn_regions",
            field=models.ManyToManyField(blank=True, to="exploration.worldregion"),
        ),
        migrations.AddField(
            model_name="battle",
            name="enemy_fleet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="battles",
                to="combat.piratefleet",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="battleturn",
            unique_together={("battle", "turn_number")},
        ),
    ]
