# Generated by Django 5.2.5 on 2025-09-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='loot_earned',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='npc_attack_power',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='battle',
            name='npc_defense',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='battle',
            name='npc_health',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='battle',
            name='npc_max_health',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='battle',
            name='npc_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='battle',
            name='npc_type',
            field=models.CharField(default='pirate', max_length=50),
        ),
    ]
